<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LidUtils.Core\LidUtils.Core.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.19" />
  </ItemGroup>
</Project>

